version: "3.9"

networks:
  siec: {}

services:
  baza_mdb:
    image: mariadb:10.10.2
    container_name: baza_mdb
    networks:
      - siec
    environment:
      MARIADB_USER: dawidw
      MARIADB_PASSWORD: dawidw
      MARIADB_ROOT_PASSWORD: rootroot
    user: "1000:1000"
    volumes:
      - "/home/dawidw/Docker_Directories/db:/var/lib/mysql"
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --connect
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 30s
  apache:
    image: dawid/php:8.1-apache-mysqli
    networks:
      - siec
    volumes:
      - "/home/dawidw/Docker_Directories/www:/var/www/html"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    ports:
      - "9000:80"
    links:
      - baza_mdb
    depends_on:
      baza_mdb:
        condition: service_healthy
